/** Shared currency utilities — used by the wizard and the dashboard. */

export const CURRENCIES: { code: string; symbol: string; name: string }[] = [
  { code: "AFN", symbol: "؋",     name: "Afghan Afghani" },
  { code: "ALL", symbol: "L",     name: "Albanian Lek" },
  { code: "DZD", symbol: "دج",    name: "Algerian Dinar" },
  { code: "AOA", symbol: "Kz",    name: "Angolan Kwanza" },
  { code: "ARS", symbol: "$",     name: "Argentine Peso" },
  { code: "AMD", symbol: "֏",     name: "Armenian Dram" },
  { code: "AWG", symbol: "ƒ",     name: "Aruban Florin" },
  { code: "AUD", symbol: "A$",    name: "Australian Dollar" },
  { code: "AZN", symbol: "₼",     name: "Azerbaijani Manat" },
  { code: "BSD", symbol: "B$",    name: "Bahamian Dollar" },
  { code: "BHD", symbol: "BD",    name: "Bahraini Dinar" },
  { code: "BDT", symbol: "৳",     name: "Bangladeshi Taka" },
  { code: "BBD", symbol: "Bds$",  name: "Barbadian Dollar" },
  { code: "BYN", symbol: "Br",    name: "Belarusian Ruble" },
  { code: "BZD", symbol: "BZ$",   name: "Belize Dollar" },
  { code: "XOF", symbol: "CFA",   name: "West African CFA Franc" },
  { code: "XAF", symbol: "FCFA",  name: "Central African CFA Franc" },
  { code: "BMD", symbol: "BD$",   name: "Bermudian Dollar" },
  { code: "BTN", symbol: "Nu",    name: "Bhutanese Ngultrum" },
  { code: "BOB", symbol: "Bs.",   name: "Bolivian Boliviano" },
  { code: "BAM", symbol: "KM",    name: "Bosnian Convertible Mark" },
  { code: "BWP", symbol: "P",     name: "Botswanan Pula" },
  { code: "BRL", symbol: "R$",    name: "Brazilian Real" },
  { code: "GBP", symbol: "£",     name: "British Pound Sterling" },
  { code: "BND", symbol: "B$",    name: "Brunei Dollar" },
  { code: "BGN", symbol: "лв",    name: "Bulgarian Lev" },
  { code: "BIF", symbol: "Fr",    name: "Burundian Franc" },
  { code: "KHR", symbol: "៛",     name: "Cambodian Riel" },
  { code: "CAD", symbol: "CA$",   name: "Canadian Dollar" },
  { code: "CVE", symbol: "Esc",   name: "Cape Verdean Escudo" },
  { code: "KYD", symbol: "KY$",   name: "Cayman Islands Dollar" },
  { code: "CLP", symbol: "CL$",   name: "Chilean Peso" },
  { code: "CNY", symbol: "¥",     name: "Chinese Yuan" },
  { code: "COP", symbol: "CO$",   name: "Colombian Peso" },
  { code: "KMF", symbol: "CF",    name: "Comorian Franc" },
  { code: "CDF", symbol: "FC",    name: "Congolese Franc" },
  { code: "CRC", symbol: "₡",     name: "Costa Rican Colón" },
  { code: "CUP", symbol: "$MN",   name: "Cuban Peso" },
  { code: "CZK", symbol: "Kč",    name: "Czech Koruna" },
  { code: "DKK", symbol: "kr",    name: "Danish Krone" },
  { code: "DJF", symbol: "Fdj",   name: "Djiboutian Franc" },
  { code: "DOP", symbol: "RD$",   name: "Dominican Peso" },
  { code: "EGP", symbol: "E£",    name: "Egyptian Pound" },
  { code: "ERN", symbol: "Nfk",   name: "Eritrean Nakfa" },
  { code: "ETB", symbol: "Br",    name: "Ethiopian Birr" },
  { code: "EUR", symbol: "€",     name: "Euro" },
  { code: "FKP", symbol: "£",     name: "Falkland Islands Pound" },
  { code: "FJD", symbol: "FJ$",   name: "Fijian Dollar" },
  { code: "XPF", symbol: "Fr",    name: "CFP Franc" },
  { code: "GMD", symbol: "D",     name: "Gambian Dalasi" },
  { code: "GEL", symbol: "₾",     name: "Georgian Lari" },
  { code: "GHS", symbol: "GH₵",   name: "Ghanaian Cedi" },
  { code: "GIP", symbol: "£",     name: "Gibraltar Pound" },
  { code: "GTQ", symbol: "Q",     name: "Guatemalan Quetzal" },
  { code: "GNF", symbol: "Fr",    name: "Guinean Franc" },
  { code: "GYD", symbol: "G$",    name: "Guyanese Dollar" },
  { code: "HTG", symbol: "G",     name: "Haitian Gourde" },
  { code: "HNL", symbol: "L",     name: "Honduran Lempira" },
  { code: "HKD", symbol: "HK$",   name: "Hong Kong Dollar" },
  { code: "HUF", symbol: "Ft",    name: "Hungarian Forint" },
  { code: "ISK", symbol: "kr",    name: "Icelandic Króna" },
  { code: "INR", symbol: "₹",     name: "Indian Rupee" },
  { code: "IDR", symbol: "Rp",    name: "Indonesian Rupiah" },
  { code: "IRR", symbol: "﷼",     name: "Iranian Rial" },
  { code: "IQD", symbol: "ع.د",   name: "Iraqi Dinar" },
  { code: "ILS", symbol: "₪",     name: "Israeli New Shekel" },
  { code: "JMD", symbol: "J$",    name: "Jamaican Dollar" },
  { code: "JPY", symbol: "¥",     name: "Japanese Yen" },
  { code: "JOD", symbol: "JD",    name: "Jordanian Dinar" },
  { code: "KZT", symbol: "₸",     name: "Kazakhstani Tenge" },
  { code: "KES", symbol: "KSh",   name: "Kenyan Shilling" },
  { code: "KWD", symbol: "KD",    name: "Kuwaiti Dinar" },
  { code: "KGS", symbol: "с",     name: "Kyrgystani Som" },
  { code: "LAK", symbol: "₭",     name: "Laotian Kip" },
  { code: "LBP", symbol: "L£",    name: "Lebanese Pound" },
  { code: "LSL", symbol: "L",     name: "Lesotho Loti" },
  { code: "LRD", symbol: "L$",    name: "Liberian Dollar" },
  { code: "LYD", symbol: "LD",    name: "Libyan Dinar" },
  { code: "MGA", symbol: "Ar",    name: "Malagasy Ariary" },
  { code: "MWK", symbol: "MK",    name: "Malawian Kwacha" },
  { code: "MYR", symbol: "RM",    name: "Malaysian Ringgit" },
  { code: "MVR", symbol: "Rf",    name: "Maldivian Rufiyaa" },
  { code: "MRU", symbol: "UM",    name: "Mauritanian Ouguiya" },
  { code: "MUR", symbol: "₨",     name: "Mauritian Rupee" },
  { code: "MXN", symbol: "MX$",   name: "Mexican Peso" },
  { code: "MDL", symbol: "L",     name: "Moldovan Leu" },
  { code: "MNT", symbol: "₮",     name: "Mongolian Tögrög" },
  { code: "MAD", symbol: "MAD",   name: "Moroccan Dirham" },
  { code: "MZN", symbol: "MT",    name: "Mozambican Metical" },
  { code: "MMK", symbol: "K",     name: "Myanmar Kyat" },
  { code: "NAD", symbol: "N$",    name: "Namibian Dollar" },
  { code: "NPR", symbol: "₨",     name: "Nepalese Rupee" },
  { code: "NZD", symbol: "NZ$",   name: "New Zealand Dollar" },
  { code: "NIO", symbol: "C$",    name: "Nicaraguan Córdoba" },
  { code: "NGN", symbol: "₦",     name: "Nigerian Naira" },
  { code: "KPW", symbol: "₩",     name: "North Korean Won" },
  { code: "MKD", symbol: "ден",   name: "North Macedonian Denar" },
  { code: "NOK", symbol: "kr",    name: "Norwegian Krone" },
  { code: "OMR", symbol: "OMR",   name: "Omani Rial" },
  { code: "PKR", symbol: "₨",     name: "Pakistani Rupee" },
  { code: "PAB", symbol: "B/.",   name: "Panamanian Balboa" },
  { code: "PGK", symbol: "K",     name: "Papua New Guinean Kina" },
  { code: "PYG", symbol: "₲",     name: "Paraguayan Guaraní" },
  { code: "PEN", symbol: "S/",    name: "Peruvian Sol" },
  { code: "PHP", symbol: "₱",     name: "Philippine Peso" },
  { code: "PLN", symbol: "zł",    name: "Polish Złoty" },
  { code: "QAR", symbol: "QR",    name: "Qatari Rial" },
  { code: "RON", symbol: "lei",   name: "Romanian Leu" },
  { code: "RUB", symbol: "₽",     name: "Russian Ruble" },
  { code: "RWF", symbol: "FRw",   name: "Rwandan Franc" },
  { code: "SHP", symbol: "£",     name: "Saint Helena Pound" },
  { code: "WST", symbol: "T",     name: "Samoan Tala" },
  { code: "STN", symbol: "Db",    name: "São Tomé & Príncipe Dobra" },
  { code: "SAR", symbol: "SR",    name: "Saudi Riyal" },
  { code: "RSD", symbol: "din.",  name: "Serbian Dinar" },
  { code: "SCR", symbol: "₨",     name: "Seychellois Rupee" },
  { code: "SLE", symbol: "Le",    name: "Sierra Leonean Leone" },
  { code: "SGD", symbol: "S$",    name: "Singapore Dollar" },
  { code: "SBD", symbol: "SI$",   name: "Solomon Islands Dollar" },
  { code: "SOS", symbol: "Sh",    name: "Somali Shilling" },
  { code: "ZAR", symbol: "R",     name: "South African Rand" },
  { code: "KRW", symbol: "₩",     name: "South Korean Won" },
  { code: "SSP", symbol: "£",     name: "South Sudanese Pound" },
  { code: "LKR", symbol: "₨",     name: "Sri Lankan Rupee" },
  { code: "SDG", symbol: "ج.س.",  name: "Sudanese Pound" },
  { code: "SRD", symbol: "SR$",   name: "Surinamese Dollar" },
  { code: "SZL", symbol: "L",     name: "Swazi Lilangeni" },
  { code: "SEK", symbol: "kr",    name: "Swedish Krona" },
  { code: "CHF", symbol: "CHF",   name: "Swiss Franc" },
  { code: "SYP", symbol: "£S",    name: "Syrian Pound" },
  { code: "TWD", symbol: "NT$",   name: "New Taiwan Dollar" },
  { code: "TJS", symbol: "SM",    name: "Tajikistani Somoni" },
  { code: "TZS", symbol: "TSh",   name: "Tanzanian Shilling" },
  { code: "THB", symbol: "฿",     name: "Thai Baht" },
  { code: "TOP", symbol: "T$",    name: "Tongan Paʻanga" },
  { code: "TTD", symbol: "TT$",   name: "Trinidad & Tobago Dollar" },
  { code: "TND", symbol: "DT",    name: "Tunisian Dinar" },
  { code: "TRY", symbol: "₺",     name: "Turkish Lira" },
  { code: "TMT", symbol: "T",     name: "Turkmenistani Manat" },
  { code: "AED", symbol: "AED",   name: "UAE Dirham" },
  { code: "UGX", symbol: "USh",   name: "Ugandan Shilling" },
  { code: "UAH", symbol: "₴",     name: "Ukrainian Hryvnia" },
  { code: "USD", symbol: "$",     name: "United States Dollar" },
  { code: "UYU", symbol: "$U",    name: "Uruguayan Peso" },
  { code: "UZS", symbol: "сўм",   name: "Uzbekistani Som" },
  { code: "VUV", symbol: "VT",    name: "Vanuatu Vatu" },
  { code: "VES", symbol: "Bs.S",  name: "Venezuelan Bolívar" },
  { code: "VND", symbol: "₫",     name: "Vietnamese Dong" },
  { code: "YER", symbol: "﷼",     name: "Yemeni Rial" },
  { code: "ZMW", symbol: "ZK",    name: "Zambian Kwacha" },
  { code: "ZWL", symbol: "Z$",    name: "Zimbabwean Dollar" },
];

const _symbolMap = new Map(CURRENCIES.map((c) => [c.code, c.symbol]));

/** Returns the display symbol for an ISO 4217 code, falling back to the code itself. */
export function getCurrencySymbol(code: string | null | undefined): string {
  if (!code) return "";
  return _symbolMap.get(code) ?? code;
}

/** Returns a compact number formatter for the given currency code. */
export function makeFmt(currency: string | null | undefined) {
  const sym = getCurrencySymbol(currency);
  return (n: number): string => {
    if (n >= 1_000_000) {
      const v = n / 1_000_000;
      return `${sym}${v.toLocaleString(undefined, { minimumFractionDigits: 1, maximumFractionDigits: 1 })}M`;
    }
    if (n >= 1_000) {
      const v = n / 1_000;
      return `${sym}${v.toLocaleString(undefined, { minimumFractionDigits: 1, maximumFractionDigits: 1 })}K`;
    }
    return `${sym}${Math.round(n).toLocaleString()}`;
  };
}
